title: 肉とお米とブロッコリー
author: makietan
description: 日報を中心に、技術メモやイベント参加記録をまとめるブログです。
lang: 'ja'
locale: ja_JP

# minima footer/social compatibility
twitter_username: makietanx
github_username: makietan

rss: rss

url: https://makietan.github.io

baseurl: ""

markdown: kramdown

kramdown:
  input: GFM
  gfm_emojis: true

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

logo: /assets/images/icon_144.png

twitter:
  username: makietanx

github:
  username: makietan

social:
  name: makietan
  links:
    - https://github.com/makietan
    - https://twitter.com/makietanx

google_analytics: true
google_adsense: true
bing_webmaster: true

timezone: Asia/Tokyo

future: false

exclude: ["README.md", "CONTRIBUTING.md", ".travis.yml", "Gemfile", "Gemfile.lock", ".updated", "Rakefile", "vendor", "tmp", "lib", "LICENSE", ".textlintrc", "package-lock.json", "package.json", "node_modules", ".vscode"]

show_excerpts: true

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

related_post_count: 5
